version: '3'

services:
  php:
    build: ./app
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./app/conf/php.ini:/usr/local/etc/php/php.ini
      - ./log/xdebug:/var/log/xdebug
    depends_on: 
      - db

  db:
   image: mariadb
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: rootpassword
   container_name: mariadb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    container_name: adminer